export const ProductColor = {
  ORANGE: '#FFEDD4',
  GREEN: '#D8F999',
  BLUE: '#CEFAFE',
} as const

export type ProductColor = (typeof ProductColor)[keyof typeof ProductColor]

export const ProductCategory = {
  BEBIDAS: 'Bebidas',
  TRUFAS: 'Trufas',
  BARRAS: 'Barras',
} as const

export type ProductCategory =
  (typeof ProductCategory)[keyof typeof ProductCategory]

export interface Product {
  id: string
  description: string
  price: number
  color: ProductColor
  category: ProductCategory
}

export const products: Product[] = [
  {
    id: '001',
    description: 'Trufa maracujá 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '002',
    description: 'Trufa maracujá 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '003',
    description: 'Trufa coco 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '004',
    description: 'Trufa coco 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '005',
    description: 'Trufa morango 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '006',
    description: 'Trufa morango 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '007',
    description: 'Trufa chocolate 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '008',
    description: 'Trufa chocolate 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '009',
    description: 'Trufa avelã 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '010',
    description: 'Trufa avelã 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '011',
    description: 'Trufa tradicional 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '012',
    description: 'Trufa tradicional 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '013',
    description: 'Trufa amendoim 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '014',
    description: 'Trufa amendoim 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '015',
    description: 'Trufa doce de leite 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '016',
    description: 'Trufa doce de leite 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '017',
    description: 'Trufa limão 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '018',
    description: 'Trufa limão 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '019',
    description: 'Trufa café 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '020',
    description: 'Trufa café 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '021',
    description: 'Trufa baunilha 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '022',
    description: 'Trufa baunilha 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '023',
    description: 'Trufa pistache 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '024',
    description: 'Trufa pistache 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '025',
    description: 'Trufa castanha 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '026',
    description: 'Trufa castanha 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '027',
    description: 'Trufa laranja 30g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '028',
    description: 'Trufa laranja 35g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '029',
    description: 'Trufa maracujá 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '030',
    description: 'Trufa coco 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '031',
    description: 'Trufa morango 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '032',
    description: 'Trufa chocolate 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '033',
    description: 'Trufa avelã 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '034',
    description: 'Trufa tradicional 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '035',
    description: 'Trufa amendoim 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '036',
    description: 'Trufa doce de leite 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '037',
    description: 'Trufa limão 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '038',
    description: 'Trufa café 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '039',
    description: 'Trufa baunilha 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '040',
    description: 'Trufa pistache 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '041',
    description: 'Trufa castanha 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '042',
    description: 'Trufa laranja 40g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '043',
    description: 'Trufa maracujá 45g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '044',
    description: 'Trufa coco 45g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '045',
    description: 'Trufa morango 45g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '046',
    description: 'Trufa chocolate 45g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '047',
    description: 'Trufa avelã 45g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '048',
    description: 'Trufa tradicional 45g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '049',
    description: 'Trufa amendoim 45g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '050',
    description: 'Trufa doce de leite 45g',
    price: 9.99,
    color: ProductColor.GREEN,
    category: ProductCategory.TRUFAS,
  },
  {
    id: '051',
    description: 'Café',
    price: 6.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },
  {
    id: '052',
    description: 'Café grande',
    price: 7.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },
  {
    id: '053',
    description: 'Café com leite',
    price: 8.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },
  {
    id: '054',
    description: 'Capuccino',
    price: 9.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },
  {
    id: '055',
    description: 'Chocolate quente',
    price: 10.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },
  {
    id: '056',
    description: 'Suco laranja',
    price: 9.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },
  {
    id: '057',
    description: 'Suco limão',
    price: 9.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },
  {
    id: '058',
    description: 'Suco maracujá',
    price: 9.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },
  {
    id: '059',
    description: 'Suco morango',
    price: 9.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },
  {
    id: '060',
    description: 'Suco abacaxi',
    price: 9.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },
  {
    id: '099',
    description: 'Chocolate gelado',
    price: 12.99,
    color: ProductColor.ORANGE,
    category: ProductCategory.BEBIDAS,
  },

  {
    id: '100',
    description: 'Barra chocolate 30g',
    price: 12.99,
    color: ProductColor.BLUE,
    category: ProductCategory.BARRAS,
  },
  {
    id: '101',
    description: 'Barra chocolate 40g',
    price: 13.99,
    color: ProductColor.BLUE,
    category: ProductCategory.BARRAS,
  },
  {
    id: '102',
    description: 'Barra chocolate 50g',
    price: 14.99,
    color: ProductColor.BLUE,
    category: ProductCategory.BARRAS,
  },
  {
    id: '103',
    description: 'Barra chocolate 60g',
    price: 15.99,
    color: ProductColor.BLUE,
    category: ProductCategory.BARRAS,
  },
  {
    id: '104',
    description: 'Barra chocolate 70g',
    price: 16.99,
    color: ProductColor.BLUE,
    category: ProductCategory.BARRAS,
  },
  {
    id: '150',
    description: 'Barra chocolate 150g',
    price: 29.99,
    color: ProductColor.BLUE,
    category: ProductCategory.BARRAS,
  },
]
